### PR TITLE
Add minute based aggregation of pokemon activity to heatmap

### PR DESCRIPTION
**Pull request by rollator**
This PR adds a slider below the heatmap(both normal and single report) when it's activated. The slider can be used to adjust the data which is used for the heatmap, based on the minute on which the pokemon spawned or was active. For example if the slider's set to 30, all pokemon with the minute of the expire_timestamp being between 30 and 45 are used, as a pokemon is active for 15 minutes.

### CODE REVIEW

**Comment by rollator** [comment]
the heatmap now also takes the hour of the day into account and hence it's a 24 hour slider(10 minute steps)

**Comment by DavidSelem** [comment]
Looks awesome!

**Comment by plague180** [comment]
That is awesome!

**Comment by modrzew** [comment]
@rollator I slightly adjusted code style and merged it. Thanks!

**Comment by rollator** [comment]
Great, thanks :D

**Pull request merged**
