### PR TITLE
Added directions link to pokemon popup

### PR DESCRIPTION
**Pull request by YonderGod**

### CODE REVIEW

**Comment by paul30001** [comment]
How do I update my Pokeminer? Isn't it an uneditable package? Do I have to run virtualenv?

**Comment by Baklap4** [comment]
@paul30001 you can update your Pokeminer by using `git pull` in the place where you've cloned your repository

**Comment by paul30001** [comment]
@Baklap4 What syntax would I use? `git pull+[What URL?]` or just `git pull`?

**Comment by Baklap4** [comment]
@paul30001 just `git pull`. Are you on windows, osx or linux? And did you clone this repo or downloaded a zip?

https://git-scm.com/book/en/v2/Getting-Started-Git-Basics

**Comment by YonderGod** [comment]
@paul30001 I don't understand what you're asking. I don't see anywhere to download Pokeminer not as source code.

**Comment by Baklap4** [comment]
Just a suggestion:
Maybe it's a good thing to write a tutorial on how to get this up and running on multiple platforms? A good place for this would be at the wiki ;)

**Comment by YonderGod** [comment]
This specific pull request that we are commenting on is very simple.

Just click 'files changed' above, and add/change the 3 lines in /templates/newmap.html

**Comment by YonderGod** [comment]
And I just noticed I derped
`var lat = item.lon;`
should obviously be
`var lon = item.lon;`

**Comment by modrzew** [comment]
Thanks!

**Pull request merged**
