### PR TITLE
Added web hook support

### PR DESCRIPTION
**Pull request by Brideau**
This pull request adds support for an arbitrary number of webhook endpoints to work with Pokeminer. I did my best to match the overall structure of your code.

The data structure of data sent to the listeners is identical to that used by PokemonGo-Map, so it will be instantly compatible with any webhook listener built by 3rd-parties for PGM.

I tested this by using it with two http://requestb.in/ endpoints and Pokelyzer, running the scan with two accounts. It successfully posted its results to all three endpoints.

Webhook endpoints are included in the config.py file through a list of strings, where each string represents one endpoint.

The only additional libraries required in the `worker.py` file were "requests" (which is already in the requirements.txt file), the native base 64 encoder, and the native calendar package for timestamp conversion.

### CODE REVIEW

**Comment by freakjam** [comment]
Tested this pull request and wanted to let you guys know it works perfectly fine for me.
Running on CentOS 7 + Pokeminer + Pokelyzer.

**Comment by chuparCh0pper** [comment]
What I changed in the config.py is 
`DB_ENGINE = 'postgresql://pokemon_go_role:MYPW@localhost:5432/pokemon_go'`
and
`WEBHOOK_ENDPOINTS = ['http://localhost:9876']`
but I'm getting
```
ProgrammingError: (psycopg2.ProgrammingError) relation "forts" does not exist
LINE 2: FROM forts 
             ^
 [SQL: 'SELECT forts.id AS forts_id, forts.external_id AS forts_external_id, forts.lat AS forts_lat, forts.lon AS forts_lon \nFROM forts \nWHERE forts.external_id = %(external_id_1)s AND forts.lat = %(lat_1)s AND forts.lon = %(lon_1)s \n LIMIT %(param_1)s'] [parameters: {'external_id_1': u'ce6b7a4f0bdf43838ebd730d33459dea.16', 'param_1': 1, 'lon_1':
```

**Comment by Brideau** [comment]
@chuparCh0pper For this integration, you only need to change `WEBHOOK_ENDPOINTS`. The DB_ENGINE for pokeminer will remain the same. On top of saving it to its own database, it sends the data to any services listening on the web hooks, like Pokelyzer, which then saves it to its own database.

**Comment by modrzew** [comment]
@Brideau thanks for the PR, I like it.

BUT! unfortunately it won't be compatible with what I'm doing on `coroutines` branch. Specifically, I mean [DatabaseProcessor](https://github.com/modrzew/pokeminer/blob/coroutines/worker.py#L465) which workers talk to - they no longer need access to database, as it's blocking; instead, they just push seen Pokemon and gyms to processor's queue, and go forward. Processor then (in separate thread) figures out which things should be put in the database.

Could you rewrite it in a similar fashion?

**Comment by Brideau** [comment]
@modrzew Let me know when that branch has been finalized, just so I'm not programming against a moving target. Shouldn't be much effort to adapt it.

**Comment by BallTongue0** [comment]
I get:
```
    WEBHOOK_ENDPOINTS = [http://localhost:9876]
                             ^
SyntaxError: invalid syntax
```

After i've changed the webhook endpoint... What should i point it to? I want pokelyzer to get the data...

**Comment by Aiyubi** [comment]
@BallTongue0 its python so I guess without looking into it: you are missing the backticks ['http://localhost:9876']

**Comment by subzerofun** [comment]
@Brideau Hey thanks for the webhook code, as @modrzew said the coroutines branch has a different worker.py code. I know you said you don´t want to code against moving target, but could you share the updated code for this branch in this chat – if you have already written it? i tried it myself, but can´t get it to work...

**Pull request closed without merging**
