### PR TITLE
caps disappear time to 15 minutes

### LINKED ISSUE #219: Over 35690min left on timer
I don't know what happened but i restarted my workers and started the web.py and about 20% of all pokemons have a really long time left to despawn, i don't mind if it's a graphical bug but I'm worried that it will mess up the database...

### PR DESCRIPTION
**Pull request by snicker**
fixes #219 and #220 

per the recommendation here, these anomalies are in the scope of the consumer to fix
https://github.com/AeonLucid/POGOProtos/pull/184

### CODE REVIEW

**Comment by Aiyubi** [comment]
this is the wrong fix... this way you get wrong disappear times into your database.

**Comment by snicker** [comment]
Okay, that does sound like a better approach. @seikur0, have you confirmed that those sightings eventually show the correct time?

**Comment by seikur0** [comment]
Not for 1x60 spawns, that spawn every hour one pokemon for one hour. These have a wrong tth at all times and won't get detected at all. But that's the design decision of modrzew. I'm not using pokeminer, just saw that issue and fixed it, so the map will have exactly the same behavior as before the overflow.

**Comment by Aiyubi** [comment]
@seikur0 will 60 min spawns not appear like 15 min pokemon when time_till_hidden_ms is below 15 minutes?

**Comment by seikur0** [comment]
No, they won't. If you want some kind of explanation, I'd say this: time_till_hidden_ms is the time until the spawn point is empty and only sent as a valid time, if it's below 15 min. Since a 1x60 spawn point is never empty, it never gets a valid tth.

**Comment by modrzew** [comment]
@seikur0 isn't time_till_hidden_ms related to a Pokemon and not to a spawn point? Won't 60 minute spawn send proper time_till_hidden_ms when there's less than 15 minutes for it to disappear?

**Comment by seikur0** [comment]
You'd think so, but no. 60 minutes spawns never send a proper tth.

**Pull request closed without merging**
