### PR TITLE
Db threading

### PR DESCRIPTION
**Pull request by Aiyubi**
Fixed 2 issues about multithreading db access:
* only write db when ordered to (no autoflush)
* lock threading while writing db

### CODE REVIEW

**Comment by Aiyubi** [comment]
downside: this makes the project even more vulnerable to #44 . If it fails during database flush, all threads will stop

**Comment by modrzew** [comment]
I had reservations about that because it could make workers put duplicated entries to database. But then I remembered that I've been working on a simple app cache to store all current sightings to limit queries sent to database, and this PR looks promising. I'll get to it as soon as I'm done rewriting worker to use [tejado/pgoapi](https://github.com/tejado/pgoapi) directly.

**Comment by techdough** [comment]
this definitely helped fix the issue by synchronizing it. However when I was doing my own research it seems that scoped_session are recommended to create a thread safe session, But, when I used scoped_sessions I still got the same errors. 
http://docs.sqlalchemy.org/en/latest/orm/contextual.html

**Comment by Aiyubi** [comment]
@modrzew if you want to avoid such database problems in general you will have to implement more thread locks:
* whenever you flush something to the database (so no autoflush and every pokemon write 
* whenever you read from the databse until you have processed the result. So if you check a group of pokemon being in the database you need to lock from the first check until your results have finished writing to the database.

**Comment by modrzew** [comment]
@Aiyubi you need to rebase. Moreover, does it still fit with the most recent additions to master - especially the application cache? There will be much less SELECTs than before.

**Pull request closed without merging**
