### PR TITLE
Makes single-pokemon report image not blurry

### PR DESCRIPTION
**Pull request by diceroll123**
Turns this:
chrome_2016-08-26_02-07-05

Into this:
chrome_2016-08-26_02-07-40

Quite powerful with a small bit of ~~code~~ CSS.

### CODE REVIEW

**Comment by modrzew** [comment]
:open_mouth:

Sadly [it's supported in IE with `-ms-` prefix and not supported at all in Edge](http://caniuse.com/#search=image-rendering). But hey, who cares about those, right?

**Comment by diceroll123** [comment]
Oh, right, not everyone uses chrome...

**Comment by modrzew** [comment]
Some use Firefox - me, for example :wink:

**Comment by diceroll123** [comment]
:unamused: Because I'm a kind soul.

**Pull request closed without merging**
