### PR TITLE
Display spawnpoints

### PR DESCRIPTION
**Pull request by Aiyubi**
Currently working on:
- config values

**TODO List:**
- [X] add spawnpoint markers to the map
- [X] add a popup with information about spawns on that point
- [X] load spawnpoint popup data only once it gets clicked
- [X] nice formating of the popup
- [X] summary mode for popups
- [X] clustering!
- [x] fix double entrys by adding group by normalized timestamp
- [ ] set startdate for popup analysis (currently takes all data)
- [ ] config.spawnarealimits

**to improve list:**
- nice image for the spawnpoints (I got so used to those points)
- the tables will linebreak because the scrollbar gets added after width calculation. Tried some things but could not get it working. 
- options to customize popup

**Screenshot of WIP (already updated since this pic)**
wipspawnpoints

### CODE REVIEW

**Comment by modrzew** [comment]
I like it! Should I do the code review, or should I wait with it until you're happy with its shape?

**Comment by Aiyubi** [comment]
@modrzew todo list is on 2/6 - and some of the code will be touched with clustering. Guess I will have done most tomorrow evening

**Comment by Innenseide** [comment]
Oh boy, I'm **very** excited for this!

Do you see any way to include an aggregate of spawn numbers per Pokemon, without cluttering the thing too much? So from the example of your screenshot it could display something like
> Hornliu: 3 (50%)
> Rattfratz: 2 (33,3%)
> Zubat: 1 (16,6%)

**Comment by Aiyubi** [comment]
Yes that is the goal in the long run. Also a classification may be included (blue dots for points that get classified as water)
But one step after the other

**Comment by FFroehlich** [comment]
I am currently working on a classifcation algorithm which could be integrated with pokeminer (see https://www.reddit.com/r/pokemongodev/comments/4xfw9r/biomes_debunked/)
I am currently rewriting my matlab code prototype to python, which is now almost done, so this might be possible to do in the not so distant future

**Comment by Aiyubi** [comment]
@FFroehlich that post was the reason I started this! When you are ready to show something I would be happy to review it.

**Comment by Aiyubi** [comment]
@modrzew code quality has gone down in the last commits but I will not have much time to code the rest of the week; so I released what I had. Top post has my thoughts on what could be improved.

Also one note: if you use this with python 2.7 there are ascii errors again which I ignored since the project is going 3.5

**Comment by Aiyubi** [comment]
okay couldn't sleep, so added clustering and its amazing! performance has gone way up!

**Comment by fxbt** [comment]
I just try it and it's very nice!

I was using it with python 2.7 and as expected, i got an ascii error. With python 3, no problem.

Simple suggestion, it would be nice to not display the filtered pokemon (those in the TRASH_IDS) array as they add a lot of unnecessary data.

**Comment by Aiyubi** [comment]
@fxbt I really intended something different. It is intended to show all data - this way you can see if there was a skipped spawn or not.

Also what if you have a spawn that only spawned trash? Would this point not be displayed? This way you kind of loose information.

**Pull request closed without merging**
