### PR TITLE
Compression of Images and Making the Small Versions Match the Larger Icon Counterparts

### PR DESCRIPTION
**Pull request by LordLioath**

### CODE REVIEW

**Comment by modrzew** [comment]
@GaelicGamer what other options regarding Pokemon icons are there? Those are fine, but I think current ones are more readable. Though definitely going down from 16KB to 0.2KB per icon is another story.

**Comment by GaelicGamer** [comment]
If you prefer the other Icons I could run those through it instead, just wasn't sure which were preferred honestly, additionally might want to look into loading the icons externally due to possible copyright claims that could stem from them.

**Comment by modrzew** [comment]
@GaelicGamer sorry for delay. Either BW or HGSS sprites look nice.

Do you do anything else with the images besides pngcrushing them?

**Comment by GaelicGamer** [comment]
No just pngcrushing them atm, they were already made correctly so there wasn't any need for that icon set to need any other alterations, I'll take a look at the BW and HGSS sprites when I can and do those instead.

**Pull request closed without merging**
